# Generated by Django 6.0.1 on 2026-02-10 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('category', models.CharField(max_length=100)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('totalAmount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentType', models.CharField(max_length=50)),
                ('paymentStatus', models.CharField(max_length=50)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.customer')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.customer')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorid', models.AutoField(primary_key=True, serialize=False)),
                ('shopname', models.CharField(max_length=100)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.vendor'),
        ),
    ]
